// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcUynUx_Bd5_yRgLaR3_yRjoqW252wRKI',
    appId: '1:331894919295:web:1635815ef73530ba776f4a',
    messagingSenderId: '331894919295',
    projectId: 'login-flutter-29e72',
    authDomain: 'login-flutter-29e72.firebaseapp.com',
    databaseURL: 'https://login-flutter-29e72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-flutter-29e72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJp21l7RSwmKaXUYhfrmjOEY52ggTv2Gg',
    appId: '1:331894919295:android:c30b30fcdd3bb6a3776f4a',
    messagingSenderId: '331894919295',
    projectId: 'login-flutter-29e72',
    databaseURL: 'https://login-flutter-29e72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-flutter-29e72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOqYAG2dNV7yiKz-Z0yGk-ET6obh81a8',
    appId: '1:331894919295:ios:6cee6986e06198e0776f4a',
    messagingSenderId: '331894919295',
    projectId: 'login-flutter-29e72',
    databaseURL: 'https://login-flutter-29e72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-flutter-29e72.appspot.com',
    iosBundleId: 'com.example.earthquake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnOqYAG2dNV7yiKz-Z0yGk-ET6obh81a8',
    appId: '1:331894919295:ios:9e79e4ba424d3041776f4a',
    messagingSenderId: '331894919295',
    projectId: 'login-flutter-29e72',
    databaseURL: 'https://login-flutter-29e72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-flutter-29e72.appspot.com',
    iosBundleId: 'com.example.earthquake.RunnerTests',
  );
}
